/* This script will create a table called spotify_tbl
if the table exists already the query will drop it immediately*/

DROP TABLE IF EXISTS spotify_tbl
CREATE TABLE spotify_tbl(
[Artist] NVARCHAR(MAX),
[Track] NVARCHAR(MAX),
[Album] NVARCHAR(MAX),
[Album_type] NVARCHAR(MAX),
[Danceability] FLOAT,
[Energy] FLOAT,
[Loudness] FLOAT,
[Speechiness] FLOAT,
[Acousticness] FLOAT,
[Instrumentalness] FLOAT,
[Liveness] FLOAT,
[Valence] FLOAT,
[Tempo] FLOAT,
[Duration_min] FLOAT,
[Title] NVARCHAR(MAX),
[Channel] NVARCHAR(MAX),
[Views] BIGINT,
[Likes] BIGINT,
[Comments] BIGINT,
[Licensed] NVARCHAR(MAX),
[official_video] NVARCHAR(MAX),
[Stream] BIGINT,
[EnergyLiveness] FLOAT,
[most_playedon] NVARCHAR(MAX)
)

INSERT INTO spotify_tbl(
[Artist],
[Track],
[Album],
[Album_type] ,
[Danceability] ,
[Energy] ,
[Loudness] ,
[Speechiness] ,
[Acousticness] ,
[Instrumentalness] ,
[Liveness] ,
[Valence] ,
[Tempo] ,
[Duration_min] ,
[Title] ,
[Channel] ,
[Views] ,
[Likes] ,
[Comments] ,
[Licensed] ,
[official_video] ,
[Stream] ,
[EnergyLiveness] ,
[most_playedon] 
)

SELECT
	Artist,
	Track,
	Album,
	Album_type,
	CAST(Danceability AS FLOAT),
	CAST(Energy AS FLOAT),
	CAST(Loudness AS FLOAT),
	CAST(Speechiness AS FLOAT),
	CAST(Acousticness AS FLOAT),
	CAST(Instrumentalness AS FLOAT),
	CAST(Liveness AS FLOAT),
	CAST(Valence AS FLOAT),
	CAST(Tempo AS FLOAT),
	CAST(Duration_min AS FLOAT),
	Title,
	Channel,
	CAST(Views AS BIGINT),
	CAST(Likes AS BIGINT),
	CAST(Comments AS BIGINT),
	Licensed,
	official_video,
	CAST(Stream AS BIGINT),
	CAST(EnergyLiveness AS FLOAT),
	most_playedon
FROM spotify
